TODO/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("todo_list.urls", namespace="todo_list")),
]

todo_list/urls.py
from django.urls import path
from todo_list.views import *


urlpatterns = [
    path("", TaskList.as_view(), name="task-list"),
    path("tags/", TagList.as_view(), name="tag-list"),
    path('tags/<int:pk>/undo', undo_task, name='undo-task'),
    path("tags/create", TagCreate.as_view(), name="tag-create"),
    path("task/create", TaskCreate.as_view(), name="task-create"),
    path('tags/<int:pk>/complete', complete_task, name='complete-task'),
    path("tags/<int:pk>/update", TagUpdate.as_view(), name="tag-update"),
    path("tags/<int:pk>/delete", TagDelete.as_view(), name="tag-delete"),
    path("task/<int:pk>/update", TaskUpdate.as_view(), name="task-update"),
    path("task/<int:pk>/delete", TaskDelete.as_view(), name="task-delete"),
]

app_name = "todo_list"

todo_list/models.py
from django.db import models


class Tag(models.Model):
    title = models.CharField(max_length=63)

    def __str__(self):
        return self.title


class Task(models.Model):
    content = models.TextField()
    was_created = models.DateTimeField(auto_now_add=True)
    deadline = models.DateTimeField(null=True, default=None)
    status = models.BooleanField(default=False)
    tags = models.ManyToManyField(Tag)

    class Meta:
        ordering = ['status', 'was_created']

    def __str__(self):
        return self.content

todo_list/forms.py
from django.forms import ModelForm
from todo_list.models import Task, Tag


class TaskForm(ModelForm):
    class Meta:
        model = Task
        fields = ['content', 'tags']


class TagForm(ModelForm):
    class Meta:
        model = Tag
        fields = '__all__'

todo_list/views.py
from django.shortcuts import get_object_or_404, redirect
from todo_list.forms import TagForm, TaskForm
from todo_list.models import Task, Tag
from django.urls import reverse_lazy
from django.views import generic


def undo_task(request, pk):
    task = get_object_or_404(Task, pk=pk)

    if request.method == 'POST':
        task.is_done = False
        task.save()
        return redirect(reverse_lazy('todo_list:task-list'))
    return redirect(reverse_lazy('todo_list:task-list'))


def complete_task(request, pk):
    task = get_object_or_404(Task, pk=pk)
    if request.method == 'POST':
        task.is_done = True
        task.save()
        return redirect(reverse_lazy('todo_list:task-list'))
    return redirect(reverse_lazy('todo_list:task-list'))


class TaskList(generic.ListView):
    model = Task
    context_object_name = "task_list"
    template_name = "todo_list/task_list.html"
    queryset = Task.objects.prefetch_related("tags")


class TaskCreate(generic.CreateView):
    model = Task
    form_class = TaskForm
    template_name = "todo_list/task_form.html"
    success_url = reverse_lazy("todo_list:task-list")


class TaskDelete(generic.DeleteView):
    model = Task
    fields = "__all__"
    template_name = "todo_list/task_delete.html"
    success_url = reverse_lazy("todo_list:task-list")


class TaskUpdate(generic.UpdateView):
    model = Task
    form_class = TaskForm
    template_name = "todo_list/task_form.html"
    success_url = reverse_lazy("todo_list:task-list")


class TagList(generic.ListView):
    model = Tag
    context_object_name = "tag_list"
    template_name = "todo_list/tag_list.html"


class TagCreate(generic.CreateView):
    model = Tag
    form_class = TagForm
    template_name = "todo_list/tag_form.html"
    success_url = reverse_lazy("todo_list:tag-list")


class TagDelete(generic.DeleteView):
    model = Tag
    fields = "__all__"
    template_name = "todo_list/tag_delete.html"
    success_url = reverse_lazy("todo_list:tag-list")


class TagUpdate(generic.UpdateView):
    model = Tag
    form_class = TagForm
    template_name = "todo_list/tag_form.html"
    success_url = reverse_lazy("todo_list:tag-list")

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block title %}
        <title>Title</title>
    {% endblock %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css" integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">
</head>
<body>
{% include 'includes/sidebar.html' %}
{% block content %}
{% endblock %}
</body>
</html>

templates/includes/sidebar.html
<ul class="list-group">
  <li class="list-group-item"><a href="{% url 'todo_list:task-list' %}">Home</a></li>
  <li class="list-group-item"><a href="{% url 'todo_list:tag-list' %}">Tags</a></li>
</ul>

templates/todo_list/tag_delete.html
{% extends "base.html" %}

{% block content %}

    <h1>Delete tag</h1>


    <p>Are you sure you want to delete the tag {{ tag }}</p>

    <form action="" method="post">
    {% csrf_token %}
        <input type="submit" value="Yes, delete" class="btn btn-danger">
    </form>
{% endblock %}

templates/todo_list/tag_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
    <h1>{{ object|yesno:"Update,Create" }} Tag</h1>

    <form action="" method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <input class="btn btn-primary" type="submit" value="submit">
    </form>
{% endblock %}

templates/todo_list/tag_list.html
{% extends "base.html" %}

{% block content %}
    <h1>Tags</h1>
    <button style="float: right; margin-right: 25px; bottom: 50px; position:relative;" class="btn btn-primary">
        <a role="button" style="color: white"
           href="{% url 'todo_list:tag-create'%}">Add</a>
    </button>

    {% if tag_list %}
        <table class="table">
            <tr>
                <th>Name</th>
                <th>Update</th>
                <th>Delete</th>
            </tr>
            {% for tag in tag_list %}
                <tr>
                    <td>{{ tag.title }}</td>
                    <td>
                        <button style="background: gray" class="btn"><a role="button" style="color: white"
                                                                        href="{% url 'todo_list:tag-update' pk=tag.id %}">Update</a>
                        </button>
                    </td>
                    <td>
                        <button style="background: gray" class="btn"><a role="button" style="color: white"
                                                                        href="{% url 'todo_list:tag-delete' pk=tag.id %}">Delete</a>
                        </button>
                    </td>

                </tr>
            {% endfor %}

        </table>

    {% else %}
        <p>Empty list</p>
    {% endif %}

{% endblock %}

templates/todo_list/task_delete.html
{% extends "base.html" %}

{% block content %}

    <h1>Delete task</h1>

    <p>Are you sure you want to delete the task {{ task }}</p>

    <form action="" method="post">
    {% csrf_token %}
        <input type="submit" value="Yes, delete" class="btn btn-danger">
    </form>
{% endblock %}

templates/todo_list/task_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
    <h1>{{ object|yesno:"Update,Create" }} Task</h1>

    <form action="" method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <input class="btn btn-primary" type="submit" value="submit">
    </form>
{% endblock %}

templates/todo_list/task_list.html
{% extends "base.html" %}

{% block content %}
    <h1>TODO list</h1>
    <button style="float: right" class="btn-primary"
            type="submit"
            value="submit">
        <a role="button" style="color: white"
           href="{% url 'todo_list:task-create' %}">Add task</a>
    </button>
    <br>

    {% if task_list %}
        {% for task in task_list %}
            <br>
            <div class="form-group">
                <b>{{ task.content }}</b>

                {% if task.is_done %}
                    <b><span class="done">Done</span></b>
                    <form method="post" action="{% url 'todo_list:undo-task' pk=task.id %}">
                        {% csrf_token %}

                        <button style="float: right" type="submit" class="btn btn-blurred">
                            Undo
                        </button>

                    </form>

                {% else %}
                    <b><span class="not-done">Not done</span></b>

                    <form method="post" action="{% url 'todo_list:complete-task' pk=task.id %}">
                        {% csrf_token %}

                        <button style="float: right" type="submit" class="btn">
                            Complete
                        </button>
                    </form>

                {% endif %}

            </div>
            <div class="form-group">
                Created: {{ task.created_at }} {% if task.deadline %}
                <span class="text-deadline">Deadline: {{ task.deadline }}</span>
            {% endif %}
            </div>
            <div class="form-group">
                <b><span class="text-tag"> Tags:
                    {% for tag in task.tags.all %}
                        {{ tag.title }}
                    {% endfor %}
                </span></b>

                <br>
                <a href="{% url 'todo_list:task-update' pk=task.id %}">Update</a>
                <a href="{% url 'todo_list:task-delete' pk=task.id %}">Delete</a>
            </div>
        {% endfor %}

    {% else %}
        <p>Empty list</p>
    {% endif %}



{% endblock %}